version: '3.8'

x-docker-data: &env-variables
    TEST_DATA: 'Hello world!'

services:

    production-php-fpm:
        image: ghcr.io/saschati/github-docker:php-fpm${DOCKER_IMAGE_TAG}
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app

    production-php-cli:
        image: ghcr.io/saschati/github-docker:php-cli${DOCKER_IMAGE_TAG}
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app
