version: '3.8'

x-docker-data: &env-variables
    TEST_ENV: 'env'

services:

    production-php-fpm:
        image: ghcr.io/saschati/github-docker:php-fpm
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app

    production-php-cli:
        image: ghcr.io/saschati/github-docker:php-cli
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app
