version: '3.8'

x-docker-data: &env-variables
    TEST_ENV: 'env'

services:

    production-php-fpm:
        image: docker.pkg.github.com/saschati/github-docker/php-fpm:latest
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app

    production-php-cli:
        image: docker.pkg.github.com/saschati/github-docker/php-cli:latest
        environment:
            <<: *env-variables
        volumes:
            - ./app:/app
