name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  TAG: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker php-fpm
        id: meta-php-fpm
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/php-fpm

      - name: Extract metadata (tags, labels) for Docker php-cli
        id: meta-php-cli
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/php-cli

      - name: Build and push Docker php-fpm image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:./app/docker"
          dockerfile: app/docker/development/php-fpm/Dockerfile
          push: true
          tags: ${{ steps.meta-php-fpm.outputs.tags }}
          labels: ${{ steps.meta-php-fpm.outputs.labels }}
#          tags: ${{ env.REGISTRY }}/php-fpm:${{ env.TAG }},${{ env.REGISTRY }}/php-fpm:latest

      - name: Build and push Docker php-cli image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:./app/docker"
          dockerfile: app/docker/development/php-cli/Dockerfile
          push: true
          tags: ${{ steps.meta-php-cli.outputs.tags }}
          labels: ${{ steps.meta-php-cli.outputs.labels }}
#          tags: ${{ env.REGISTRY }}/php-cli:${{ env.TAG }},${{ env.REGISTRY }}/php-cli:latest

      - name: Show TAG
        run: |
          echo "${{ env.TAG }}"