name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  TAG: $(git rev-parse --short HEAD)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker php-fpm image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: app/docker
          dockerfile: development/php-fpm/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/php-fpm:${{ env.TAG }},${{ env.REGISTRY }}/php-fpm:latest

      - name: Build and push Docker php-cli image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: app/docker
          dockerfile: development/php-cli/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/php-cli:${{ env.TAG }},${{ env.REGISTRY }}/php-cli:latest

      - name: Show TAG
        run: |
          echo "${{ env.TAG }}"